### ISSUE TITLE
Has this repo been superceded by chef-provisioning-ssh?

### ISSUE THREAD

**Issue by westbywest** [double-z/chef-metal-ssh#10]
Given the chef-metal / chef-provisioning renaming, am I correct in guessing that this repo would replace chef-metal-ssh?
https://github.com/double-z/chef-provisioning-ssh

**Comment by double-z** [comment]
yes, this repo has been replaced by chef-provisioning-ssh as you mentioned. Please note that the `:machine_options` have changed quite a bit from this version to that... please adjust accordingly.
